config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # Health check
  get "/up", to: "application#up"

  scope module: "users" do
    resources :expenses, only: [:index, :create, :show, :edit, :update, :destroy]
    resources :expense_destroy, only: [:show]
    resources :monthly_expenses_breakdown, only: [:show], param: :date

    ### CUSTOM AUTHENTICATION ROUTES BELOW

    # Registration
    get "/sign_up", to: "registrations#new"
    post "/sign_up", to: "registrations#create"

    # Sessions
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    delete "/sessions/:id", to: "sessions#destroy", as: :destroy_user_session

    # Reset passwords
    get "/forgot-my-password", to: "reset_passwords#new"
    post "/forgot-my-password", to: "reset_passwords#create"
    get "/reset-my-password/:token", to: "reset_passwords#edit", as: :edit_reset_my_password
    patch "/reset-my-password/:token", to: "reset_passwords#update", as: :update_reset_my_password

    # Confirmation emails
    get "/users/confirmation", to: "confirmations#new"
    post "/users/confirmation", to: "confirmations#create"
    get "/users/confirmation/:token", to: "confirmations#edit", as: :edit_user_confirmation
    patch "/users/confirmation/:token", to: "confirmations#update", as: :update_user_confirmation

    get "/settings", to: "settings#edit"

    # Change emails
    patch "/settings/update_email", to: "settings#request_email_update", as: :user_request_email_update
    get "/settings/update_email/:token", to: "settings#update_email", as: :user_settings_update_email

    # Change passwords
    patch "/settings/passwords", to: "passwords#update", as: :update_user_password
  end

  root "root#index"
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  has_many :tokens, class_name: "UserToken", dependent: :delete_all

  has_many :expenses, dependent: :destroy

  validates :email, uniqueness: true
  validates :password, presence: true, length: (8..72)

  scope :confirmed, -> { where.not(confirmed_at: nil) }
  scope :unconfirmed, -> { where(confirmed_at: nil) }

  def active_sessions
    tokens.where(context: UserToken::CONTEXTS[:session])
  end

  def confirmation_tokens
    tokens.where(context: UserToken::CONTEXTS[:confirmation])
  end

  def change_email_tokens
    tokens.where("starts_with(context, 'change:')")
  end

  def confirm!
    update_column :confirmed_at, Time.current
  end
end

app/controllers/api/v1/users/sessions_controller.rb
module Api::V1::Users
  class SessionsController
    def create
    end

    def destroy
    end

    private

    def user_params
      params.require(:user).permit(:email, :password)
    end
  end
end

app/controllers/users/application_controller.rb
module Users
  class ApplicationController < ::ApplicationController
    # Base controller for any controller that requires a User to be authenticated
    before_action :require_user_authentication!
  end
end

app/controllers/users/channels_controller.rb
module Users
  class ChannelsController < ApplicationController
    def show
      channel = Webrtc::Channel.find(params[:id])
      render locals: {channel: channel}
    end
  end
end

app/controllers/users/confirmations_controller.rb
module Users
  class ConfirmationsController < ::ApplicationController
    before_action :find_user_by_confirmation_token, only: [:edit, :update]

    def new
    end

    def create
      if user = User.unconfirmed.find_by(email: params[:email])
        user_token = UserToken.create_confirmation_token!(user)
        UserMailer.with(user: user, token: user_token.encoded_token).confirmation.deliver_later
      end

      flash[:notice] = "If your email address exists in our database, you will receive an email with instructions on how to confirm your account in a few minutes."
      redirect_to users_login_url
    end

    def edit
    end

    def update
      @user.confirm! unless @user.confirmed_at?
      @user.confirmation_tokens.delete_all

      flash[:notice] = "Successfully confirmed your account."
      redirect_to users_login_url
    end

    private

    def find_user_by_confirmation_token
      @token = params[:token]

      if @token.present? && !(@user = UserToken.find_user_by_confirmation_token(@token))
        flash[:alert] = "The link might have expired or is invalid."
        redirect_to users_login_url
      end
    end
  end
end

app/controllers/users/conversations_controller.rb
module Users
  class ConversationsController < ApplicationController
    def index
      conversations = Conversation.includes(:conversation_participants).where({conversation_participants: {participant: current_user}})
      render locals: {conversations: conversations}
    end

    def show
      conversation = Conversation.includes(:conversation_participants).where({conversation_participants: {participant: current_user}}).find(params[:id])
      messages = conversation.messages.includes(:sender)
      render layout: "conversations", locals: {conversation: conversation, messages: messages}
    end
  end
end

app/controllers/users/expense_destroy_controller.rb
module Users
  class ExpenseDestroyController < ApplicationController
    def show
      expense = current_user.expenses.find(params[:id])
      render locals: {expense: expense}
    end
  end
end

app/controllers/users/expenses_controller.rb
module Users
  class ExpensesController < ApplicationController
    before_action :set_date_viewed

    def index
      new_expense = current_user.expenses.new
      date_scoped_expenses = current_user.expenses.where(date: @date_viewed, disabled_at: nil)

      obj = ExpensesBreakdown.new(user: current_user, date: @date_viewed)
      obj.maybe_create_monthly_expenses
      dates_with_expenses = obj.dates_with_expenses

      render locals: {date_scoped_expenses:, new_expense:, dates_with_expenses:}
    end

    def show
      expense = current_user.expenses.find(params[:id])
      render locals: {expense: expense}
    end

    def create
      expense = current_user.expenses.new(expense_params)

      if expense.save
        redirect_to expenses_url(date: expense.date), notice: "Logged"
      else
        redirect_to expenses_url(date: expense.date), alert: "Failed to log the expense"
      end
    end

    def edit
      expense = current_user.expenses.find(params[:id])
      render locals: {expense: expense}
    end

    def update
      expense = current_user.expenses.find(params[:id])

      expense.update(update_params)
      render locals: {expense: expense}
    end

    def destroy
      expense = current_user.expenses.find(params[:id])
      result = ExpenseDestroyer.new.destroy(expense, params[:destroy_option])

      respond_to do |format|
        format.turbo_stream { render locals: {expense: result.expense} }
        format.html { redirect_to expenses_url, notice: "Successfully delete the expense" }
      end
    end

    private

    def expense_params
      params.require(:expense).permit(:date, :purpose, :amount, :recurring)
    end

    def update_params
      params.require(:expense).permit(:amount)
    end

    def set_date_viewed
      @date_viewed = Date.parse(params[:date])
    rescue
      @date_viewed = Date.current
    end
  end
end

app/controllers/users/invite_token_controller.rb
module Users
  class InviteTokenController < ApplicationController
    def update
      current_user.invite_token.regenerate_token
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to settings_url, alert: "Updated your invite token!" }
      end
    end
  end
end

app/controllers/users/messages_controller.rb
module Users
  class MessagesController < ApplicationController
    include ConversationScoped

    def create
      result = MessageCreator.new.create_message(@conversation, current_user, message_params)
      if result.created?
        head :ok
      else
        head :unprocessable_entity
      end
    end

    private

    def message_params
      params.require(:message).permit(:body)
    end
  end
end

app/controllers/users/monthly_expenses_breakdown_controller.rb
module Users
  class MonthlyExpensesBreakdownController < ApplicationController
    def index
    end

    def show
      date = Date.parse(params[:date])
      breakdown = ExpensesBreakdown.new(user: current_user, date: date)

      render locals: {
        date: date,
        expenses: breakdown.daily_expenses,
        misc_total: breakdown.misc_total,
        monthly_recurring_total: breakdown.monthly_recurring_total,
        total_for_month: breakdown.total_for_month,
        no_expenses_this_month: breakdown.no_expenses_this_month?
      }
    end
  end
end

app/controllers/users/passwords_controller.rb
module Users
  class PasswordsController < ApplicationController
    def update
      password = Password.new(password_params.merge({has_secure_password: current_user}))
      if password.save
        redirect_to users_settings_url, notice: "Successfully changed your password."
      else
        respond_to do |format|
          format.html { redirect_to users_settings_url, alert: "Failed to change your password." }
          format.turbo_stream do
            render locals: {password: password}, status: :unprocessable_entity
          end
        end
      end
    end

    private

    def password_params
      params.require(:password).permit(:current_password, :password, :password_confirmation)
    end
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < ::ApplicationController
    before_action :redirect_if_already_authenticated!

    def new
      render locals: {user: User.new}
    end

    def create
      user = User.new(user_params)

      if user.save
        user_token = UserToken.create_confirmation_token!(user)
        UserMailer.with(user: user, token: user_token.encoded_token).confirmation.deliver_later

        flash[:notice] = "You will receive email confirmation instructions in few minutes."
        redirect_to users_login_url
      else
        render :new, locals: {user: user}, status: :unprocessable_entity
      end
    end

    private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
  end
end

app/controllers/users/reset_passwords_controller.rb
module Users
  class ResetPasswordsController < ApplicationController
    skip_before_action :require_user_authentication!
    before_action :redirect_if_already_authenticated!
    before_action :find_user_by_reset_password_token, only: [:edit, :update]

    def new
    end

    def create
      if user = User.confirmed.find_by(email: params[:email])
        user_token = UserToken.create_reset_password_token!(user)
        UserMailer.with(user: user, token: user_token.encoded_token).reset_password.deliver_later
      end

      flash[:notice] = "If your email address exists in our database, you will receive an email with instructions on how to reset your password in a few minutes."
      redirect_to users_login_url
    end

    def edit
    end

    def update
      if @user.update(password_params)
        @user.tokens.delete_all
        flash[:notice] = "Successfully reset your password!"
        redirect_to users_login_url
      else
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def find_user_by_reset_password_token
      @token = params[:token]

      if @token.present? && !(@user = UserToken.find_user_by_reset_password_token(@token))
        flash[:alert] = "The link might have expired or is invalid."
        redirect_to users_login_url
      end
    end

    def password_params
      params.require(:user).permit(:password, :password_confirmation)
    end
  end
end

app/controllers/users/sessions_controller.rb
module Users
  class SessionsController < ::ApplicationController
    include UserAuthentication
    before_action :redirect_if_already_authenticated!, only: [:new, :create]

    def new
    end

    def create
      if (user = User.confirmed.find_by(email: params[:email])&.authenticate(params[:password]))
        redirect_url = stored_url || root_url
        reset_session
        token = UserToken.create_session_token!(user)
        session[:user_token] = token
        redirect_to redirect_url, notice: "Logged in successfully."
      else
        flash.now[:alert] = "Invalid email/password."
        render :new, status: :unprocessable_entity
      end
    end

    def destroy
      if (token_id = params[:id])
        token = @current_user&.active_sessions&.find_by(id: token_id)&.destroy
        respond_to do |format|
          format.turbo_stream { render locals: {token: token} } if token
          format.html { redirect_to users_settings_url, notice: "Successfully removed the session" }
        end
      else
        @current_user&.active_sessions&.delete_all
        reset_session
        redirect_to users_login_url, notice: "Logged out successfully."
      end
    end
  end
end

app/controllers/users/settings_controller.rb
module Users
  class SettingsController < ApplicationController
    before_action :find_change_email_token, only: [:update_email]

    def edit
      password = Password.new(has_secure_password: current_user)
      render locals: {active_sessions: current_user.active_sessions, password: password}
    end

    def request_email_update
      new_email = params[:email]

      error_message =
        if new_email == current_user.email
          error_message = "That is already your email!"
        elsif User.where(email: new_email).exists?
          error_message = "Email is already taken."
        end

      if error_message
        redirect_to users_settings_url, alert: error_message
      else
        user_token = UserToken.create_change_email_token!(current_user, new_email)
        UserMailer.with(receiver_email: new_email, token: user_token.encoded_token).update_email.deliver_later
        redirect_to users_settings_url, notice: "A link to confirm your email has been sent to the new address."
      end
    end

    def update_email
      current_user.update_column :email, @user_token.sent_to
      current_user.change_email_tokens.delete_all
      redirect_to users_settings_url, notice: "Successfully changed your email."
    end

    private

    def find_change_email_token
      token = params[:token]
      @user_token = UserToken.find_record_by_user_change_email_token(current_user, token)

      unless @user_token
        redirect_to users_settings_url, alert: "The email change link is invalid or it has expired."
      end
    end
  end
end

app/views/users/expenses/_expense.html.erb
<%= turbo_frame_tag dom_id(expense) do %>
  <article class="shadow-sm p-2 mb-2" data-controller="clickable" data-action="click->clickable#click" role="button">
    <p class="p-0 m-0 mb-2">
      <span class="text-danger fw-bold">-<%= number_to_pesos(expense.amount_from_cents) %></span>
      <br />
      <span class="fw-light fst-italic"><%= expense.purpose %></span>
    </p>

    <% if expense.errors.any? %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <% expense.errors.full_messages.each do |error_msg| %>
          <%= error_msg %> <br />
        <% end %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>

    <div class="d-flex">
      <%= link_to "Edit", edit_expense_path(expense), class: "btn btn-sm btn-secondary me-2 d-none", data: {clickable_target: "linkToFollow"} %>
    </div>
  </article>
<% end %>

app/views/users/expenses/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(expense) %>

app/views/users/expenses/edit.html.erb
<%= turbo_frame_tag dom_id(expense) do %>
  <article class="shadow-sm p-2 mb-2">
    <p class="p-0 m-0 fw-light fst-italic">
      <%= expense.purpose %>
    </p>

    <%= form_with(id: dom_id(expense, :edit), model: expense, method: :put, url: expense_path(expense), data: {turbo_frame: "navigation"}) do |form| %>
      <div class="mb-2">
        <%= form.label :amount, class: "form-label" %>
        <%= form.number_field :amount, value: expense.amount_from_cents, class: "form-control", step: "0.01" %>
      </div>
    <% end %>
    <div class="d-flex">
      <%= link_to "Cancel", expense_path(expense), class: "btn btn-sm btn-warning me-2" %>
      <%= button_tag(form: dom_id(expense, :edit), type: :submit, class: "btn btn-sm btn-secondary me-2") do %>
        Update
      <% end %>
      <% if expense.recurring %>
        <%= link_to "Delete", expense_destroy_path(expense), class: "btn btn-sm btn-danger" %>
      <% else %>
        <%= form_with(model: expense, url: expense_path(expense), method: :delete, data: {turbo_confirm: "Are you sure?"}) do |form| %>
          <%= button_tag "Delete", type: "submit", name: "destroy_option", value: :this_instance, class: "btn btn-sm btn-danger" %>
        <% end %>
      <% end %>
    </div>
  </article>
<% end %>

app/views/users/expenses/index.html.erb
<h1>Expenses Logger</h1>
<div class="row">
  <div class="col-md-4">
    <%= link_to "Breakdown for #{@date_viewed.strftime("%B")}", monthly_expenses_breakdown_path(@date_viewed), class: "btn btn-sm btn-primary mb-2 text-white" %>
    <div data-controller="calendar" class="table-responsive">
      <%= calendar(date: @date_viewed, marked_dates: dates_with_expenses, path_method: :expenses_path) %>
    </div>
  </div>
  <div class="col-md-8 border border-dark">
    <h2 class="fs-4 mt-2">Log an expense</h2>
    <%= form_with(model: new_expense, url: expenses_path, method: :post) do |form| %>
      <%= form.hidden_field :date, value: @date_viewed %>
      <div class="mb-2">
        <%= form.label :purpose, class: "form-label" %>
        <%= form.text_field :purpose, class: "form-control" %>
      </div>
      <div class="mb-2">
        <%= form.label :amount, class: "form-label" %>
        <%= form.number_field :amount, class: "form-control", step: "0.01" %>
      </div>
      <div class="mb-2">
        <%= form.label :recurring, "Recurring (optional)", class: "form-label" %>
        <%= form.select :recurring, Expense.recurrings.transform_keys(&:capitalize), {include_blank: true}, {class: "form-select"} %>
      </div>
      <%= form.submit "Log", class: "btn btn-primary text-white" %>
    <% end %>
  </div>
</div>

<hr />

<% if date_scoped_expenses.size < 1 %>
  <article>
    <h1>No Expenses for <%= month_day_year_for_date(@date_viewed) %><h1>
  </article>
<% else %>
  <section>
    <h1>Expenses for <%= month_day_year_for_date(@date_viewed) %></h1>
    <% date_scoped_expenses.each do |expense| %>
      <%= render partial: "expense", locals: {expense: expense} %>
    <% end %>
  </section>
<% end %>

app/views/users/expenses/show.html.erb
<%= render partial: "expense", locals: {expense: expense} %>

app/views/users/expenses/update.html.erb
<%= render partial: "expense", locals: {expense: expense} %>